# Generated by Django 3.2.6 on 2021-08-28 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZoonList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoon_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(max_length=20, unique=True)),
                ('office_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.zoonlist')),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('office_name', models.CharField(max_length=100)),
                ('office_address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('employee_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.office')),
            ],
        ),
    ]
