# Generated by Django 3.2.6 on 2021-08-28 16:03

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_office_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='employee_id',
        ),
        migrations.AlterField(
            model_name='office',
            name='office_name',
            field=models.CharField(max_length=50, verbose_name=members.models.ZoonList),
        ),
    ]
