# Generated by Django 3.2.6 on 2021-08-28 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20210828_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='office_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.zoonlist'),
        ),
    ]
