# Generated by Django 3.2.6 on 2021-08-28 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_office_office_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='office_name',
        ),
        migrations.AddField(
            model_name='office',
            name='zoon_list',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='members.zoonlist'),
        ),
        migrations.AlterField(
            model_name='office',
            name='office_name',
            field=models.CharField(max_length=100),
        ),
    ]
