# Generated by Django 3.2.12 on 2022-03-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_members_employee_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='payment',
            field=models.IntegerField(blank=True, default='500'),
        ),
    ]
