# Generated by Django 3.2.12 on 2022-03-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20220328_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='description',
        ),
        migrations.AddField(
            model_name='members',
            name='Bio',
            field=models.CharField(default='', max_length=300),
        ),
    ]
