# Generated by Django 3.2.12 on 2022-03-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20220328_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='post',
            field=models.CharField(choices=[('Excutive Engineer', 'Excutive Engineer'), ('Sub-Divisional Engineer', 'Sub-Divisional Engineer'), ('Assistant Engineer', 'Assistant Engineer'), ('Sub-Assistant Engineer', 'Sub-Assistant Engineer')], default='', max_length=200),
        ),
    ]
