# Generated by Django 3.2.12 on 2022-03-28 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_members_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='employee_info',
        ),
    ]
