# Generated by Django 3.2.12 on 2022-03-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_remove_members_employee_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='post',
            field=models.CharField(choices=[('------Select------', '------select------'), ('Excutive Engineer', 'Excutive Engineer'), ('Sub-Divisional Engineer', 'Sub-Divisional Engineer'), ('Assistant Engineer', 'Assistant Engineer'), ('Sub-Assistant Engineer', 'Sub-Assistant Engineer')], default='', max_length=200),
        ),
    ]
