# Generated by Django 3.2.6 on 2021-08-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='father_name',
            field=models.CharField(default=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mother_name',
            field=models.CharField(default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='biodata',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(choices=[('Bangladeshi', 'Bangladeshi')], max_length=30),
        ),
    ]
