# Generated by Django 3.2.6 on 2021-08-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20210827_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='father_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mother_name',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
