# Generated by Django 3.2.6 on 2021-08-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_auto_20210828_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='father_name',
            field=models.CharField(default='Your Father name:', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mother_name',
            field=models.CharField(default='Your Mother name:', max_length=100),
        ),
    ]
