# Generated by Django 4.0.2 on 2022-03-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_user_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password2',
            field=models.CharField(help_text='comfirm password', max_length=30),
        ),
    ]
