# Generated by Django 3.2.12 on 2022-03-30 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_alter_zoonlist_zoon_name'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfo_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dipu_id', models.CharField(blank=True, max_length=30)),
                ('ideb_id', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='paymentinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paymentinfo',
            name='payIntro',
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='payIntro_1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='payintro_1', to='members.members'),
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='post',
            field=models.CharField(choices=[('------Select------', '------select------'), ('Excutive Engineer', 'Excutive Engineer'), ('Sub-Divisional Engineer', 'Sub-Divisional Engineer'), ('Assistant Engineer', 'Assistant Engineer'), ('Sub-Assistant Engineer', 'Sub-Assistant Engineer')], default='', max_length=200),
        ),
        migrations.CreateModel(
            name='PaymentInfo_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=17)),
                ('payIntro_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payintro_3', to='payment.paymentinfo_2')),
            ],
        ),
        migrations.AddField(
            model_name='paymentinfo_2',
            name='payIntro_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payintro_2', to='payment.paymentinfo'),
        ),
    ]
