# Generated by Django 3.2.10 on 2022-03-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zoon_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoon_name', models.CharField(max_length=100)),
                ('zoon_heading', models.CharField(max_length=300)),
                ('zoon_text', models.CharField(max_length=1000)),
                ('profile_img', models.ImageField(upload_to='zoon/zoon_profile')),
                ('passident_img', models.ImageField(upload_to='zoon/prasident_img')),
                ('secratary_img', models.ImageField(upload_to='zoon/prasident_img')),
            ],
        ),
    ]
